spring.application.name=springProject

# Server port Setting

server.port=8080


# DataSource MySQL
# Databse 접속 URL
# jdbc::log4jdbc:localhost:mysql
# localhost -> 접속 주소
# mysql 접속 port : 3306
# aisw -> database 이름

spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/aisw?serverTimeZone=UTC&charsetEncoding=UTF-8
spring.datasource.username=aisw
spring.datasource.password=aisw
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy


# view 위치 설정
# prefix : jsp가 있는 위치를 설정
# suffix : 확장자

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp


# MyBatis Setting

mybatis.type-aliases-package=kr.ac.tukorea
mybatis.mapper-locations==classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.return-instance-for-empty-row=true









#